'use server'

import { revalidatePath } from 'next/cache'
import { createClient } from '@supabase/supabase-js'

function getServerSupabase(): any {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

  if (!url || !key) {
    throw new Error('Missing Supabase environment variables')
  }

  return createClient(url, key)
}

async function getDefaultAgencyId(): Promise<string> {
  const supabase = getServerSupabase()

  const { data, error } = await supabase
    .from('agencies')
    .select('id')
    .order('created_at', { ascending: true })
    .limit(1)
    .maybeSingle()

  const agency = data as { id?: string } | null

  if (error) throw new Error(error.message)
  if (!agency?.id) throw new Error('Please create a demo agency in Supabase first.')

  return agency.id
}

function textValue(formData: FormData, key: string, fallback = ''): string {
  return String(formData.get(key) || fallback).trim()
}

function buildMiaMessage(lead: any): string {
  const firstName = lead?.first_name || 'there'
  const product = lead?.product || 'insurance'

  if (product === 'ACA') {
    return `Hi ${firstName}, this is MIA, the virtual assistant from MDAI Demo Medicare Agency. I received your request for ACA health insurance information. I can help gather a few basic details and connect you with a licensed agent. Are you looking for coverage for yourself or for your family?`
  }

  if (product === 'Medicare') {
    return `Hi ${firstName}, this is MIA, the virtual assistant from MDAI Demo Medicare Agency. I received your request for Medicare information. I can help gather a few basic details and connect you with a licensed agent. Are you currently enrolled in Medicare, or are you turning 65 soon?`
  }

  return `Hi ${firstName}, this is MIA, the virtual assistant from MDAI Demo Medicare Agency. I received your request for insurance information. I can help gather a few basic details and connect you with a licensed agent. Is now a good time to chat?`
}

export async function addLead(formData: FormData) {
  const supabase = getServerSupabase()
  const agencyId = await getDefaultAgencyId()

  const lead = {
    agency_id: agencyId,
    first_name: textValue(formData, 'first_name'),
    last_name: textValue(formData, 'last_name'),
    phone: textValue(formData, 'phone'),
    email: textValue(formData, 'email'),
    state: textValue(formData, 'state').toUpperCase(),
    zip_code: textValue(formData, 'zip_code'),
    product: textValue(formData, 'product', 'Medicare'),
    status: textValue(formData, 'status', 'New Lead'),
    lead_source: textValue(formData, 'lead_source', 'Manual'),
    interest_level: textValue(formData, 'interest_level', 'Unknown'),
    ai_summary: textValue(formData, 'ai_summary')
  }

  const { error } = await supabase.from('leads').insert(lead)
  if (error) throw new Error(error.message)

  revalidatePath('/')
}

export async function updateLeadStatus(formData: FormData) {
  const supabase = getServerSupabase()
  const leadId = textValue(formData, 'lead_id')
  if (!leadId) throw new Error('Missing lead id')

  const { error } = await supabase
    .from('leads')
    .update({
      status: textValue(formData, 'status', 'New Lead'),
      interest_level: textValue(formData, 'interest_level', 'Unknown'),
      ai_summary: textValue(formData, 'ai_summary'),
      last_contact_at: new Date().toISOString()
    })
    .eq('id', leadId)

  if (error) throw new Error(error.message)
  revalidatePath('/')
}

export async function generateMiaMessage(formData: FormData) {
  const supabase = getServerSupabase()
  const leadId = textValue(formData, 'lead_id')
  if (!leadId) throw new Error('Missing lead id')

  const { data: leadData, error: leadError } = await supabase
    .from('leads')
    .select('*')
    .eq('id', leadId)
    .maybeSingle()

  if (leadError) throw new Error(leadError.message)
  if (!leadData) throw new Error('Lead not found')

  const message = buildMiaMessage(leadData)

  const { error: messageError } = await supabase.from('conversations').insert({
    lead_id: leadId,
    sender: 'MIA',
    channel: 'SMS',
    message,
    ai_notes: 'Generated by MIA rule-based MVP. OpenAI connection comes next.'
  })

  if (messageError) throw new Error(messageError.message)

  const { error: updateError } = await supabase
    .from('leads')
    .update({
      status: 'AI Contacted',
      ai_summary: 'MIA generated the first outreach message. Next step: wait for customer response or schedule follow-up.',
      last_contact_at: new Date().toISOString()
    })
    .eq('id', leadId)

  if (updateError) throw new Error(updateError.message)
  revalidatePath('/')
}

export async function addCustomerReply(formData: FormData) {
  const supabase = getServerSupabase()
  const leadId = textValue(formData, 'lead_id')
  const message = textValue(formData, 'message')

  if (!leadId) throw new Error('Missing lead id')
  if (!message) throw new Error('Please enter a customer reply')

  const { error } = await supabase.from('conversations').insert({
    lead_id: leadId,
    sender: 'Customer',
    channel: 'SMS',
    message
  })

  if (error) throw new Error(error.message)
  revalidatePath('/')
}

export async function deleteLead(formData: FormData) {
  const supabase = getServerSupabase()
  const leadId = textValue(formData, 'lead_id')
  if (!leadId) throw new Error('Missing lead id')

  const { error } = await supabase.from('leads').delete().eq('id', leadId)
  if (error) throw new Error(error.message)

  revalidatePath('/')
}
